### ISSUE TITLE
Query regarding Scannet dataset config

### ISSUE THREAD

**Issue by Ramseyous0109** [spla-tam/SplaTAM#112]
Hi, I've found a small bug on the config of Scannet Dataset In `configs/data/scannet.yaml`

```yaml
dataset_name: 'scannet'
camera_params:
  image_height: 968
  image_width: 1296
  fx: 1169.621094
  fy: 1167.105103
  cx: 646.295044
  cy: 489.927032
  png_depth_scale: 1000.0
```

This intrinsic data refers to the original color images' shape. However, since the color image should be cropped to `640 × 480` to fit the size of the depth data, I think the intrinsics should also be changed [as the config in NICE-SLAM ](https://github.com/cvg/nice-slam/blob/master/configs/ScanNet/scannet.yaml)to get correct results.

```yaml
cam: 
  H: 480 
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  png_depth_scale: 1000. #for depth image in png format
```

I wonder if I get this config right. Looking forward to your reply@
